"""empty message

Revision ID: 03dc022554f0
Revises: c73fbf9869b6
Create Date: 2022-07-14 13:29:34.355959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03dc022554f0'
down_revision = 'c73fbf9869b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('test', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'test')
    # ### end Alembic commands ###
