"""empty message

Revision ID: 13a424f2042a
Revises: e5b06c99cab1
Create Date: 2022-07-14 13:17:47.045312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a424f2042a'
down_revision = 'e5b06c99cab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('test', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'test')
    # ### end Alembic commands ###
