"""empty message

Revision ID: 1836025b7ab2
Revises: 4d6b7751a15a
Create Date: 2022-07-05 13:03:35.869180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1836025b7ab2'
down_revision = '4d6b7751a15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Confirmed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Recovered', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Deceased', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Positive_result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Negative_result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='result_pkey')
    )
    # ### end Alembic commands ###
