"""empty message

Revision ID: 261afbba8ff4
Revises: 1836025b7ab2
Create Date: 2022-07-05 13:51:36.007708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261afbba8ff4'
down_revision = '1836025b7ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hospitals_HospitalName_key', 'hospitals', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hospitals_HospitalName_key', 'hospitals', ['HospitalName'])
    # ### end Alembic commands ###
