"""empty message

Revision ID: 31fa8a9fc3da
Revises: 8d1b11bd9a25
Create Date: 2022-06-29 23:26:35.236444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fa8a9fc3da'
down_revision = '8d1b11bd9a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Fname', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('Lname', sa.String(length=20), nullable=False))
    op.drop_column('patients', 'Last_Name')
    op.drop_column('patients', 'First_Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('First_Name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('Last_Name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('patients', 'Lname')
    op.drop_column('patients', 'Fname')
    # ### end Alembic commands ###
