"""empty message

Revision ID: 4236af691748
Revises: 8f10864cd70a
Create Date: 2022-07-01 20:30:15.779224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4236af691748'
down_revision = '8f10864cd70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('TestResult', sa.String(length=10), nullable=False))
    op.drop_column('patients', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'TestResult')
    # ### end Alembic commands ###
