"""empty message

Revision ID: 4d6b7751a15a
Revises: 6cff9e63ab3e
Create Date: 2022-07-01 20:41:05.660936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6b7751a15a'
down_revision = '6cff9e63ab3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'Date')
    # ### end Alembic commands ###
