"""empty message

Revision ID: 539c9fc36e04
Revises: bbe2f84afc98
Create Date: 2022-07-01 20:32:32.270230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '539c9fc36e04'
down_revision = 'bbe2f84afc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('TestResult', sa.String(length=10), nullable=True))
    op.drop_column('patients', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'TestResult')
    # ### end Alembic commands ###
