"""empty message

Revision ID: 61afec68b03b
Revises: 
Create Date: 2022-06-29 00:47:28.235327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61afec68b03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_details', sa.Column('test_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_details', 'test_col')
    # ### end Alembic commands ###
