"""empty message

Revision ID: 6d9aaf8c4b29
Revises: 0084591d4af4
Create Date: 2022-06-30 18:09:22.705683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9aaf8c4b29'
down_revision = '0084591d4af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'Date')
    # ### end Alembic commands ###
