"""empty message

Revision ID: 7c9c6fa16900
Revises: df5dd8753bfc
Create Date: 2022-06-29 19:29:34.468097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9c6fa16900'
down_revision = 'df5dd8753bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hosp_id', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Hosp_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
