"""empty message

Revision ID: 87c78e6c8561
Revises: 261afbba8ff4
Create Date: 2022-07-14 12:25:52.112045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c78e6c8561'
down_revision = '261afbba8ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('test', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'test')
    # ### end Alembic commands ###
