"""empty message

Revision ID: 8d1b11bd9a25
Revises: 7c9c6fa16900
Create Date: 2022-06-29 23:14:32.727845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1b11bd9a25'
down_revision = '7c9c6fa16900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('First_Name', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('Last_Name', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('DOB', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('Gender', sa.String(length=10), nullable=False))
    op.add_column('patients', sa.Column('Status', sa.String(length=10), nullable=False))
    op.drop_column('patients', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('patients', 'Status')
    op.drop_column('patients', 'Gender')
    op.drop_column('patients', 'DOB')
    op.drop_column('patients', 'Last_Name')
    op.drop_column('patients', 'First_Name')
    # ### end Alembic commands ###
