"""empty message

Revision ID: 8f10864cd70a
Revises: 6d9aaf8c4b29
Create Date: 2022-07-01 20:28:56.980401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f10864cd70a'
down_revision = '6d9aaf8c4b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Test_Result', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'Test_Result')
    # ### end Alembic commands ###
