"""empty message

Revision ID: bbe2f84afc98
Revises: 4236af691748
Create Date: 2022-07-01 20:31:25.731901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbe2f84afc98'
down_revision = '4236af691748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('TestResult', sa.String(length=10), nullable=False))
    op.drop_column('patients', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'TestResult')
    # ### end Alembic commands ###
