"""empty message

Revision ID: c73fbf9869b6
Revises: 13a424f2042a
Create Date: 2022-07-14 13:21:16.627750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73fbf9869b6'
down_revision = '13a424f2042a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('test', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'test')
    # ### end Alembic commands ###
