"""empty message

Revision ID: df5dd8753bfc
Revises: e5332f3cf206
Create Date: 2022-06-29 19:25:47.829843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5dd8753bfc'
down_revision = 'e5332f3cf206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('HospitalName', sa.String(length=50), nullable=False),
    sa.Column('ContactNumber', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.Column('TotalCapacity', sa.Integer(), nullable=True),
    sa.Column('ICU_Beds', sa.Integer(), nullable=True),
    sa.Column('First_Dose', sa.Integer(), nullable=True),
    sa.Column('Second_Dose', sa.Integer(), nullable=True),
    sa.Column('Precautionary_Dose', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ContactNumber'),
    sa.UniqueConstraint('HospitalName'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('Username')
    )
    op.drop_table('hospital_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('HospitalName', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ContactNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('TotalCapacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ICU_Beds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('First_Dose', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Second_Dose', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Precautionary_Dose', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hospital_details_pkey'),
    sa.UniqueConstraint('ContactNumber', name='hospital_details_ContactNumber_key'),
    sa.UniqueConstraint('HospitalName', name='hospital_details_HospitalName_key'),
    sa.UniqueConstraint('Password', name='hospital_details_Password_key'),
    sa.UniqueConstraint('Username', name='hospital_details_Username_key')
    )
    op.drop_table('hospitals')
    # ### end Alembic commands ###
