"""empty message

Revision ID: e5332f3cf206
Revises: 61afec68b03b
Create Date: 2022-06-29 00:48:17.349531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5332f3cf206'
down_revision = '61afec68b03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_details', 'test_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_details', sa.Column('test_col', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
